const kerala = [
    {
        id: 1,
        image: "https://images.unsplash.com/photo-1615133005831-ef94ee2ceb16",
        title: "Thiruvananthapuram",
        content: "Embark on a journey to Thiruvananthapuram, the vibrant capital city of Kerala, nestled on the picturesque west coast of India. Revered as the 'evergreen city' by Mahatma Gandhi, Thiruvananthapuram seamlessly blends rich history with modernity, boasting as a major IT hub alongside housing offices of central and state governments. Its illustrious past dates back to 1036 BC, marked by thriving trade in sandalwood, spices, and ivory. Under the reign of Marthandavarma, the city flourished, eventually becoming the capital of the Travancore state in the 18th century. Today, it stands as a beacon of progress with renowned institutions like ISRO and VSSC driving technological advancements. The city's geographical splendor is equally captivating, bordered by the Arabian Sea and lush districts like Kanyakumari and Kollam. With a booming economy fueled by IT and media industries, coupled with a burgeoning tourism sector, Thiruvananthapuram beckons travelers with its array of attractions—from serene beaches like Kovalam and Sanghumukham to cultural landmarks such as Napier Museum and Padmanabha Swamy Temple. Whether trekking in the Agastyakoodam hills or indulging in the tranquil waters of Neyyar Dam, Thiruvananthapuram offers an unforgettable blend of heritage, nature, and modern comforts, making it an enticing destination for explorers near and far."
    },
    {
        id: 2,
        image: "https://images.unsplash.com/photo-1579201438522-2df36892c6da",
        title: "Kollam",
        content: "Welcome to Kollam, the vibrant district often hailed as the `Capital of God's Own County.` Steeped in rich history and vibrant landscapes, Kollam stands as a testament to the confluence of lakes, sea, mountains, and lush greenery. With a storied past dating back to ancient trade relations with countries like China and the Persian Gulf, Kollam has been a thriving hub of commerce for centuries. Explore the district`s major attractions, including the legendary Ashtamudi Lake, renowned as the gateway to backwater tourism in Kerala. Experience the thrill of adventure at the scenic Adventure Park, nestled amidst the breathtaking beauty of Ashtamudi Lake. Discover serenity at the Asramam Picnic Village, spanning 48 acres and home to the Paaramparya Museum showcasing paintings from across the country. Delve into history at the Sardar Vallabhbhai Patel Police Museum, dedicated to India`s iron man and showcasing artifacts from the 18th and 19th centuries. Dive into the pristine beaches of Kollam, including the iconic Kollam Beach and Thiruvallamuram Beach, offering a perfect blend of relaxation and recreation. With easy access by air, rail, and road, including proximity to Trivandrum International Airport and the city's railway station, Kollam invites you to embark on an unforgettable journey through its cultural heritage and natural splendor. Experience the allure of Kollam and create memories to last a lifetime."
    }
    ,
    {
        id: 3,
        image: "https://images.unsplash.com/photo-1667413445864-d0c1efbb7b55",
        title: "Pathanamthitta",
        content: `Welcome to Pathanamthitta, a district in the southern part of Kerala, renowned for its rich cultural heritage and stunning natural beauty. Bordered by Thamil Nadu to the east, Kollam to the south, Alappuzha to the west, and Kottayam and Idukki to the north, Pathanamthitta offers a captivating blend of history, spirituality, and scenic landscapes. Home to the famous pilgrimage center Sabarimala, the district derives its name from the Malayalam words "Pathanam" meaning ten families and "Thitta" meaning array, reflecting its ancient roots. Once under the rule of the Pandalam dynasty with ties to the Pandya kingdom, Pathanamthitta emerged as a distinct district on November 1, 1982, incorporating territories from Kollam and Alappuzha districts. Encompassing an area of 2,637 square kilometers, half of which is lush forest cover, Pathanamthitta boasts a storied past intertwined with tales of resilience and growth. Discover the enchanting village of Gavi, known for its pristine hills, lush flora, and diverse fauna. Ideal for jungle trekkers, birdwatchers, and nature enthusiasts, Gavi offers a unique experience with night-camping amidst its verdant forests teeming with wildlife. Explore Konni, renowned for its elephant training centers and timber industry, nestled on the banks of the Achankovil River. With picturesque hills and spice plantations, Konni is emerging as a popular destination for trekking enthusiasts. Marvel at the Aruvikuzhy Waterfalls, a simple yet captivating cascade located just 11 kilometers from Kozhencherry town. Experience the spiritual aura of Sabarimala, one of Kerala's most revered Hindu pilgrimage sites, nestled amidst the Western Ghats. Visit Parumala, home to the renowned Parumala Palli, dedicated to Mar Gregorios Metropolitan, a revered saint of the Malankara Orthodox Church. Immerse yourself in the beauty of Perunthenaruvi Waterfalls, known as "The Great Honey Stream," with its majestic 60-100 feet cascade accessible by road from Pathanamthitta city. Explore the cultural gems of Aranmula, Cherukolpuzha, Kadamanitta, and Kodumon Chilanthiyambalam, each offering a glimpse into the rich tapestry of Pathanamthitta's heritage. With its captivating landscapes, spiritual sanctuaries, and vibrant culture, Pathanamthitta invites you to embark on a journey of exploration and discovery, leaving an indelible mark on your heart and soul.`
    }
    ,
    {
        id: 4,
        image: "https://images.unsplash.com/photo-1506461883276-594a12b11cf3",
        title: "Alappuzha",
        content: `
        Nestled in the southern part of Kerala, Alappuzha, formerly Alleppey, is a district renowned for its rich history and breathtaking natural beauty. Established on August 17, 1957, and renamed in 1990, Alappuzha is famed for its backwaters, coir industries, and stunning landscapes that draw tourists from far and wide. From its strategic location on the Arabian Sea to its labyrinth of rivers and canals, Alappuzha's allure is undeniable. Its past echoes through ancient towns like Kuttanad, once home to the Chera dynasty, while landmarks like the Krishnapuram Palace bear witness to its colonial legacy. With a literacy rate of 93.4% and a work participation rate of 34.3% of the state, Alappuzha covers 1414 square kilometers of sandy terrain, devoid of mountains and hills, yet teeming with cultural vibrancy. The district's climate ranges from slightly cool and dry inland to moist and temperate along the coast, fostering a diverse ecosystem. Its cultural tapestry is enriched by events like the Nehru Trophy Boat Race and festivals like Arthunkal Perunnal, while attractions like Pathiramanal Island and Alappuzha Beach offer glimpses into its natural splendor. With its blend of history, culture, and natural wonders, Alappuzha invites visitors to embark on an enchanting journey through its captivating landscapes and storied past.`
    },
    {
        id: 5,
        image: "https://e1.pxfuel.com/desktop-wallpaper/436/875/desktop-wallpaper-pin-on-kottayam-kottayam.jpg",
        title: "Kottayam",
        content: `Nestled in the heart of Kerala, Kottayam is renowned for its vibrant spice trading and is a major hub for rubber production. The city boasts a rich educational legacy, earning the title of Akshara Nagari (City of Alphabets) as the first in India to achieve 100% literacy. Known as the Land of Letters, Latex, and Lakes, Kottayam is home to leading print media headquarters, including Malayala Manorama, Deepika, and D.C. Books. Its history is steeped in significance, having played a pivotal role in modern political movements such as the Vaikom Satyagraha of 1924-25. Geographically, Kottayam is adorned with the majestic Vembanad Lake, a haven for houseboat enthusiasts and a highlight of Kerala's burgeoning tourism scene. Among its major attractions is Kumarakom, renowned for its serene lake tourism, while Pathiramanal Island serves as a sanctuary for migratory birds. Vagamon, an enchanting hill station, and other scenic spots like Aruvikkuzhi Waterfalls and Erumeli add to Kottayam's allure, making it a must-visit destination for travelers seeking natural beauty and cultural richness.`
    },
    {
        id: 6,
        image: "https://images.unsplash.com/photo-1579765338264-a74752e9a112?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        title: "Idukki",
        content: `Nestled atop the majestic Western Ghats, Idukki district in Kerala is renowned for its breathtaking landscapes and iconic dams. The district derives its name from the Malayalam word "idukku," meaning narrow space, owing to its geographical features. Formed on January 26, 1972, Idukki boasts an expansive area of 4479 square kilometers, making it the second largest district in the state. Its terrain is predominantly mountainous, with lush forests covering 97% of the area, accessible only via roadways. Idukki is celebrated for its natural wonders, offering a haven for flora and fauna enthusiasts. Among its major attractions is Munnar, a world-famous hill station that was once the summer retreat of British rulers, adorned with sprawling tea estates and captivating vistas. The district also houses the Thattekad Bird Sanctuary, Kerala's first bird sanctuary, known for its diverse avian population. The Eravikulam Wildlife Sanctuary, a national park encompassing the Anamudi peak, is famed for its rich biodiversity and the blooming of Neelakurinji flowers. Thekkady, home to the Periyar Wildlife Sanctuary, beckons travelers with its dense forests and diverse wildlife, including exotic species. Additionally, Marayur, with its historical significance and sandalwood cultivation, offers a glimpse into the region's ancient civilizations. With its abundance of natural treasures, Idukki stands as a paradise for nature lovers and adventurers alike, inviting visitors to explore its unparalleled beauty and tranquility.`
    },
    {
        id: 7,
        image: "https://images.unsplash.com/photo-1634807186335-7731bbed1e79?q=80&w=1632&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        title: "Ernakulam",
        content: "Ernakulam, holding a pivotal role in Kerala's economy, stands as the state's economic epicenter, boasting a plethora of modern amenities such as an international airport, top-notch accommodations, hospitals, educational institutions, and shopping malls. Referred to as the Queen of the Arabian Sea, Ernakulam is adorned with significant landmarks like the Kerala High Court and the Cochin Stock Exchange, epitomizing its economic prowess. The district's rich historical tapestry is woven with trade relations dating back to ancient and medieval periods, fostering connections with kingdoms like the Chera Dynasty. Under the rule of the Kingdom of Cochin, Ernakulam thrived as a cultural melting pot, welcoming Western influences that shaped its contemporary landscape. Spread across 87.341 square kilometers, Ernakulam encompasses diverse locales like Mattancherry, Palluruthy, Fort Kochi, and Kakkanad. With a population of 2,589,038 as per the 2001 census, Ernakulam boasts a cosmopolitan vibe, with Malayalam and English serving as predominant languages among a diverse religious populace. The warm tropical climate sets the stage for Ernakulam's burgeoning tourism industry, with the Cochin International Airport serving as a major gateway to Kerala. From historical landmarks like the Jewish Synagogue in Mattancherry and St. Francis Church to architectural marvels like Vallarpadam Church and Bolghatty Palace, Ernakulam offers a tapestry of cultural and religious diversity. The Hill Palace Museum stands as a testament to the region's rich heritage, while Willingdon Island serves as a bustling hub of industrial activity. Marine Drive entices visitors with its scenic charm and modern amenities, while the district's healthcare infrastructure, including renowned hospitals like Medical Trust Hospital and Lakeshore Hospital, attracts patients from far and wide. The Dutch Palace in Ernakulam showcases traditional Kerala art and architecture, while shopping enthusiasts can indulge in a world-class retail experience at destinations like Lulu Mall and Obron Mall. With its blend of historical grandeur, modernity, and cultural richness, Ernakulam stands as a beacon of progress and prosperity in Kerala."
    },
    {
        id: 8,
        image: "https://gokeralatourtravel.files.wordpress.com/2020/02/vadakkumnathan_temple.jpg?w=768",
        title: "Thrissur",
        content: "Welcome to Kollam, the vibrant district often hailed as the `Capital of God's Own County.` Steeped in rich history and vibrant landscapes, Kollam stands as a testament to the confluence of lakes, sea, mountains, and lush greenery. With a storied past dating back to ancient trade relations with countries like China and the Persian Gulf, Kollam has been a thriving hub of commerce for centuries. Explore the district`s major attractions, including the legendary Ashtamudi Lake, renowned as the gateway to backwater tourism in Kerala. Experience the thrill of adventure at the scenic Adventure Park, nestled amidst the breathtaking beauty of Ashtamudi Lake. Discover serenity at the Asramam Picnic Village, spanning 48 acres and home to the Paaramparya Museum showcasing paintings from across the country. Delve into history at the Sardar Vallabhbhai Patel Police Museum, dedicated to India`s iron man and showcasing artifacts from the 18th and 19th centuries. Dive into the pristine beaches of Kollam, including the iconic Kollam Beach and Thiruvallamuram Beach, offering a perfect blend of relaxation and recreation. With easy access by air, rail, and road, including proximity to Trivandrum International Airport and the city's railway station, Kollam invites you to embark on an unforgettable journey through its cultural heritage and natural splendor. Experience the allure of Kollam and create memories to last a lifetime."
    },
    {
        id: 9,
        image: "https://e1.pxfuel.com/desktop-wallpaper/508/748/desktop-wallpaper-palakkad-and-near-by-palakkad.jpg",
        title: "Palakkad",
        content: `Palakkad, known as the "granary of Kerala" and "Rice bowl of Kerala," stands as the gateway to the state from the north, boasting a rich tapestry of hills, rivers, mountain streams, paddy fields, and forests across its expansive 4480 square kilometers. Derived from "Pala," meaning Alsteria scholaris, and "Kadu," meaning forest, the name Palakkad encapsulates its lush natural heritage and historical significance. It serves as a pivotal nexus in trade relations between Kerala and Tamil Nadu and has made profound contributions to Kerala's art and cultural landscape. Amidst its treasures, Palakkad offers a myriad of attractions, from the historic Palakkad Fort, a testament to its storied past, to the majestic Malampuzha Dam, adorned by the Western Ghats backdrop, offering serene boating experiences. Malampuzha Garden, replete with landscaped beauty and a mesmerizing ropeway, beckons visitors to explore its charm, while Fantasy Park provides exhilarating adventures with its array of thrilling rides and attractions. Nature enthusiasts are drawn to the pristine expanse of Silent Valley National Park, teeming with diverse flora and fauna, and the expansive wilderness of Parambikulam Wildlife Sanctuary, a UNESCO World Heritage site. Nelliyampathy, with its verdant hills and picturesque plantations, offers a tranquil retreat for trekkers and adventure seekers alike. Beyond these highlights, Palakkad boasts numerous other gems, including Pothundy Dam, Mangalam Dam, and the serene expanses of Siruvani and Meenkara, ensuring an enriching and unforgettable experience for every visitor.`
    },
    {
        id: 10,
        image: "https://c1.wallpaperflare.com/preview/375/529/283/conolly-s-plot-teak-plantation-forest-nature.jpg",
        title: "Malappuram",
        content: `Malappuram district is renowned for its rich cultural heritage and historical significance, fostering a vibrant tapestry of cultural and religious attractions that have significantly contributed to Kerala's tourism. The district's famed Muslim dance form, Oppana, originates from Malappuram, while its rivers—Chaliyar, Kadalundi, and Bharathapuzha—flow gracefully, adding to its natural allure. Additionally, Malappuram boasts a deep-rooted Vedic tradition and is renowned for its Kottakkal Ayurveda treatment. With a history steeped in cultural and political movements like the Khilafat Movement and Mapila Revolt, the district's heritage sites, including the renowned Ponnani Fort, have become pivotal landmarks. Amidst its myriad attractions, travelers can explore destinations like Nilambur, famed for its teak plantations and ancient festivals, and the enchanting Nedumkayam Rainforest, ideal for immersive trekking experiences. The Kadalundi River Sanctuary offers sanctuary to migratory and native bird species, while the Adyanpara Waterfalls and Kodikuthimala beckon with their breathtaking natural beauty. Adventure enthusiasts can seek thrills at Kozhippara Waterfalls, where swimming and trekking opportunities abound. Beyond these highlights, Malappuram's picturesque hills and forests harbor gems like Keralamkundu Waterfalls and Karuvarakundu, ensuring an unforgettable journey through its enchanting landscapes.`
    },
    {
        id: 11,
        image: "https://images.unsplash.com/photo-1591018654063-90c61ce785e2?q=80&w=1427&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        title: "Kozhikode",
        content: `Formerly known as Calicut, Kozhikode district in Kerala boasts a rich and illustrious history, recognized by Arab travelers as "Kalikooth" during trade relations and often referred to as the "Cock Fort," signifying its origins as a fortified palace. The arrival of Portuguese explorer Vasco Da Gama in 1498 marked a turning point, propelling Calicut into a renowned trade center celebrated for its spices like pepper, coffee, and cardamom, earning it the title of the "City of Spices" and solidifying its role as the capital of the powerful Zamorin kingdom. Today, Kozhikode district offers a plethora of attractions, including the historic Kappad Beach, where Vasco De Gama first set foot, and the picturesque Kozhikode Beach, known for its natural beauty and historical significance. Vellari Mala's pristine landscapes beckon adventurers with its trekking trails, while Payyoli Beach offers tranquility amidst coconut-fringed shores. Tusharagiri Hills allure nature enthusiasts with captivating waterfalls and trekking opportunities, while Beypore, an ancient port town, preserves its maritime heritage, reflecting historic trade connections with the Middle East. With its blend of historical, natural, and cultural wonders, Kozhikode district promises an unforgettable journey for travelers seeking to explore Kerala's vibrant past and scenic beauty.`
    },
    {
        id: 12,
        image: "https://yatripandit.files.wordpress.com/2019/12/wayanad-2.jpg?w=825&h=510&crop=1",
        title: "Wayanad",
        content: `Wayanad, nestled in the Western Ghats along the borders of Karnataka and Tamil Nadu, boasts a rich and proud history within Kerala, emerging as the 12th district in 1980. Formerly known as Mayanadu, it covers an expanse of 2132 square kilometers and comprises three taluks: Mananthavady, Sulthan Bathery, and Vythiri. The district is adorned with prominent peaks such as Banasura Peak, Brahmagiri Peak, and Chembra Peak, which not only harbor diverse wildlife but also play a crucial role in maintaining the region's favorable climate. Flowing through Wayanad are significant rivers like the Kabini, Kaveri, Panamaram, Mananthavady, and Kalindy, with the Banasura Sagar Dam standing tall on the Kabini River. The district's predominantly hilly and forested terrain ensures a pleasant and temperate climate throughout the year, except for the warmer months of April and May, with an average annual rainfall of 3200 mm, fostering favorable conditions for agriculture and supporting Wayanad's burgeoning tourism industry. Wayanad is also home to various tribal communities, including the Kurumans, Kurichiyas, Paniyas, Kattunayakan, and Adiyas, who preserve ancient customs and lead nomadic lifestyles, constituting 36% of the Adivasi population. Among its major attractions are the breathtaking Chembra Peak, offering adventurous trekking opportunities and overnight stays, Neelimala, a picturesque spot for trekkers seeking a close encounter with nature, and the majestic Meenmutty Waterfalls, the largest in the district, where visitors can bask in the cool waters amidst the verdant forest surroundings, creating unforgettable memories of Wayanad's natural splendor.`
    },
    {
        id: 13,
        image: "https://images.unsplash.com/photo-1543198926-22fea2a870dd?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8dGhleXlhbXxlbnwwfHwwfHx8MA%3D%3D",
        title: "Kannur",
        content: `
        Kannur, also known as Cannanore, stands as the largest city in the North Malabar region, renowned for its vibrant culture and historical significance. Dubbed the "land of looms and lore," Kannur thrives with its prominent loom industry and is celebrated for the cultural art form of Theyyam. The city holds military importance, housing one of the country's military cantonments and serving as the headquarters for the Defense Security Corps and Territorial Army's 122 Infantry Battalion, affiliated with the Madras Regiment. Notably, the prestigious Ezhimala Naval Academy, ranking third globally and first in Asia, lies just 35 kilometers from Kannur. Delving into its rich history, Kannur played a pivotal role in the Middle Ages, with landmarks like St. Angelo Fort, erected in 1505 by Portuguese Viceroy Dom Franciscoo de Almeida, and later came under Dutch and British rule. It served as the capital of the Arakkal Muslim sultanate in the 17th century and witnessed the guerrilla warfare of Pazhassi Raja, leaving an indelible mark on its legacy. Among its major attractions are the formidable St. Angelo Fort, the serene Payyambalam Beach, the unique Muzhappilangad Drive-in Beach, the insightful Arakkal Museum, the picturesque Ezhimala hill, the spiritual Parassinikkadavu, and the idyllic Payyambalam Beach, offering visitors a glimpse into Kannur's rich heritage and natural beauty.`
    },
    {
        id: 14,
        image: "https://trip2kerala.com/wp-content/uploads/2021/11/Bekal.jpg",
        title: "Kasargod",
        content: `Kasaragod, situated in the northern part of Kerala, is a treasure trove of natural beauty and historical heritage. Aptly known as the "Sapthabhasha Sangamabhoomi," meaning the land where seven languages meet, the district offers a captivating blend of rivers, beaches, hillocks, forts, and shrines. The origin of its name, "Kasaragod," is steeped in history, with one belief suggesting it stems from the Sanskrit words "kaasaara," meaning lake or pond, and "kroda," signifying a place where treasure is kept. Spanning an area of 1992 square kilometers, Kasaragod is renowned for its coir and handloom products, coveted in markets worldwide, and boasts a coastline stretching 293 kilometers. With a rich historical backdrop, the district's prominence dates back to the Arab travelers of the 9th to 14th centuries, who referred to it as Harkwillia, believed to be visited by King Solomon for the collection of timbers. The Kolothiri kingdom, among others, flourished in this region. Among its major attractions is the iconic Bekal Fort, sprawling over 40 acres and offering water sports facilities at the Bekal Hole Aqua Park, while Bekal Beach, located nearby, provides a serene retreat. Chandragiri Fort, built in the 17th century by Shivappa Nayak of Bednore, stands as a testament to the region's historical significance. The Bela Church, dating back to 1890 AD, showcases Roman Gothic architecture, while the Malik Dinar Mosque serves as a revered pilgrimage site for the Muslim community. Beyond these landmarks, Kasaragod abounds in cultural and natural wonders, including the Anandashram & Nityanandasramam, Ananthapura Lake Temple, Govinda Pai Memorial, Hosdurg Fort, and the scenic Valiyaparamba, ensuring an enriching and unforgettable experience for every traveler.`
    }
]


export default kerala